---
title: "Index Sliding"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Index Sliding}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(slide)
library(dplyr)
library(nycflights13)
library(lubridate)

weather_ewr <- weather %>%
  select(origin, time_hour, temp, dewp, humid, wind_speed) %>%
  filter(origin == "EWR") %>%
  mutate(time_hour = force_tz(time_hour, "UTC")) %>%
  slice(-2, -4, -5)

weather_gap <- slice(weather_ewr, 1:5)

weather_dups <- slice(weather_ewr, 10:15)
weather_dups$time_hour[5:6] <- weather_dups$time_hour[3:4]
weather_dups$time_hour[3:4] <- weather_dups$time_hour[2]

# notice that `weather_gap` is irregular because there are missing data points.
# otherwise, the index column is still increasing, and in this case there are
# no duplicates
weather_gap

# you might watnt to compute the average temperature every 3 hours, using the
# current hour plus the 2 hours before

# with `slide_dbl()`, when `.before` is specified it looks backwards by the
# specified number of values. `slide()` and friends are not _index aware_

# mean(39.0)             | Hours: 1
# mean(39.0, 39.0)       | Hours: 1, 3
# mean(39.0, 39.0, 37.9) | Hours: 1, 3, 6
# mean(39.0, 37.9, 39.0) | Hours: 3, 6, 7
# mean(37.9, 39.0, 39.9) | Hours: 6, 7, 8
mutate(weather_gap, bad_roll_temp = slide_dbl(temp, mean, .before = 2))

# mean(39.0)             | Hours: 1
# mean(39.0, 39.0)       | Hours: 1, 3
# mean(37.9)             | Hours: 6
# mean(37.9, 39.0)       | Hours: 6, 7
# mean(37.9, 39.0, 39.9) | Hours: 6, 7, 8
mutate(weather_gap, roll_temp = slide_index_dbl(temp, time_hour, mean, .before = hours(2)))
```

