# ------------------------------------------------------------------------------

# Look backwards until index[[i]] is past range_start, then add 1 to position
# Additional check to see if the start of our window is
# already outside the last value (no data here)
locate_window_start_positive <- function(position, i, range_start, finish, complete) {
  if (complete && range_start < i[[finish]]) {
    return(NA_integer_)
  }

  while (i[[position]] >= range_start) {
    if (position == finish) {
      return(position)
    }

    position <- position - 1L
  }

  # Always goes 1 too far, so add it back afterwards
  position + 1L
}

# Look forward until index[[i]] is at or past range_start
locate_window_start_negative <- function(position, i, range_start, finish) {
  if (range_start > i[[finish]]) {
    return(NA_integer_)
  }

  while (i[[position]] < range_start) {
    if (position == finish) {
      return(position)
    }

    position <- position + 1L
  }

  position
}

# Look forward until index[[i]] is past range_stop, then subtract 1 from position
locate_window_stop_positive <- function(position, i, range_stop, finish, complete) {
  if (complete && range_stop > i[[finish]]) {
    return(NA_integer_)
  }

  while (i[[position]] <= range_stop) {
    if (position == finish) {
      return(position)
    }

    position <- position + 1L
  }

  # Always goes 1 too far, so back it off afterwards
  position - 1L
}

# Look backwards until index[[i]] is at or past range_stop
# Additional check to see if the end of our window is
# already outside the first value (no data here)
locate_window_stop_negative <- function(position, i, range_stop, finish) {
  if (range_stop < i[[finish]]) {
    return(NA_integer_)
  }

  while (i[[position]] > range_stop) {
    if (position == finish) {
      return(position)
    }

    position <- position - 1L
  }

  position
}

check_na_range <- function(x, what) {
  if (is.na(x)) {
    abort(sprintf("`NA` value detected in the index range generated by `%s`.", what))
  }

  invisible(x)
}

# ------------------------------------------------------------------------------

locate_window_start <- function(position, i, range_start, n, positive, complete) {
  if (positive) {
    locate_window_start_positive(position, i, range_start, 1L, complete)
  } else {
    locate_window_start_negative(position, i, range_start, n)
  }
}

locate_window_stop <- function(position, i, range_stop, n, positive, complete) {
  if (positive) {
    locate_window_stop_positive(position, i, range_stop, n, complete)
  } else {
    locate_window_stop_negative(position, i, range_stop, 1L)
  }
}

# ------------------------------------------------------------------------------

compute_range_starts <- function(i, before) {
  if (is_function(before)) {
    out <- before(i)
    return(out)
  }

  i - before
}

compute_range_stops <- function(i, after) {
  if (is_function(after)) {
    out <- after(i)
    return(out)
  }

  i + after
}

# ------------------------------------------------------------------------------

is_range_start_positive <- function(i_position, range_start) {
  i_position >= range_start
}

is_range_stop_positive <- function(i_position, range_stop) {
  i_position <= range_stop
}

# ------------------------------------------------------------------------------

check_index_size <- function(n, i) {
  n_i <- vec_size(i)

  if (n != n_i) {
    abort(
      sprintf("The size of `.x` (%i) and `.i` (%i) must be the same.", n, n_i)
    )
  }

  invisible()
}

check_before <- function(before) {
  if (is_unbounded(before)) {
    return(before)
  }

  if (is_formula(before, scoped = TRUE, lhs = FALSE)) {
    before <- as_function(before)
    return(before)
  }

  if (!is_function(before)) {
    vec_assert(before, size = 1L, arg = ".before")
  }

  before
}

check_after <- function(after) {
  if (is_unbounded(after)) {
    return(after)
  }

  if (is_formula(after, scoped = TRUE, lhs = FALSE)) {
    after <- as_function(after)
    return(after)
  }

  if (!is_function(after)) {
    vec_assert(after, size = 1L, arg = ".after")
  }

  after
}

check_step <- function(step) {
  step <- vec_cast(step, integer(), x_arg = ".step")
  vec_assert(step, size = 1L, arg = ".step")
  step
}

check_complete <- function(complete) {
  complete <- vec_cast(complete, logical(), x_arg = ".complete")
  vec_assert(complete, size = 1L, arg = ".complete")
  complete
}

check_params <- function(params) {
  params$before <- check_before(params$before)
  params$after <- check_after(params$after)
  params$step <- check_step(params$step)
  params$complete <- check_complete(params$complete)
  params
}

# ------------------------------------------------------------------------------

slide_index_impl <- function(.x,
                             .i,
                             .f,
                             ...,
                             .before,
                             .after,
                             .step,
                             .complete,
                             .constrain,
                             .ptype) {
  n <- vec_size(.x)
  .f <- as_function(.f)

  check_index_size(n, .i)

  params <- list(
    before = .before,
    after = .after,
    step = .step,
    complete = .complete,
    ptype = .ptype,
    constrain = .constrain,
    entry = 1L,
    position = 1L,
    n = n
  )

  params <- check_params(params)

  before_unbounded <- is_unbounded(params$before)
  after_unbounded <- is_unbounded(params$after)

  if (before_unbounded && after_unbounded) {
    loop_double_unbounded(.x, .f, params, ...)
  } else if (before_unbounded) {
    loop_before_unbounded(.x, .i, .f, params, ...)
  } else if (after_unbounded) {
    loop_after_unbounded(.x, .i, .f, params, ...)
  } else {
    loop_bounded(.x, .i, .f, params, ...)
  }
}

# ------------------------------------------------------------------------------

loop_bounded <- function(x, i, f, params, ...) {
  range_starts <- compute_range_starts(i, params$before)
  range_stops <- compute_range_stops(i, params$after)

  out <- vec_init(params$ptype, params$n)

  while(params$position <= params$n) {
    i_position <- i[[params$position]]

    range_start <- range_starts[[params$position]]
    check_na_range(range_start, ".before")

    range_stop <- range_stops[[params$position]]
    check_na_range(range_stop, ".after")

    if (range_start > range_stop) {
      range_start <- as.character(range_start)
      range_stop <- as.character(range_stop)
      abort(sprintf("In iteration %i, the start of the range, %s, cannot be after the end of the range, %s.", params$position, range_start, range_stop))
    }

    range_start_positive <- is_range_start_positive(i_position, range_start)
    window_start <- locate_window_start(params$position, i, range_start, params$n, range_start_positive, params$complete)

    if (is.na(window_start)) {
      params <- increment_by_one(params)
      next
    }

    range_stop_positive <- is_range_stop_positive(i_position, range_stop)
    window_stop <- locate_window_stop(params$position, i, range_stop, params$n, range_stop_positive, params$complete)

    if (is.na(window_stop)) {
      params <- increment_by_one(params)
      next
    }

    out <- slice_eval_assign(out, x, f, window_start, window_stop, params, ...)

    params <- increment_by_step(params)
  }

  out
}

loop_after_unbounded <- function(x, i, f, params, ...) {
  range_starts <- compute_range_starts(i, params$before)

  out <- vec_init(params$ptype, params$n)

  window_stop <- params$n

  while(params$position <= params$n) {
    i_position <- i[[params$position]]

    range_start <- range_starts[[params$position]]
    check_na_range(range_start, ".before")

    range_start_positive <- is_range_start_positive(i_position, range_start)
    window_start <- locate_window_start(params$position, i, range_start, params$n, range_start_positive, params$complete)

    if (is.na(window_start)) {
      params <- increment_by_one(params)
      next
    }

    out <- slice_eval_assign(out, x, f, window_start, window_stop, params, ...)

    params <- increment_by_step(params)
  }

  out
}

loop_before_unbounded <- function(x, i, f, params, ...) {
  range_stops <- compute_range_stops(i, params$after)

  out <- vec_init(params$ptype, params$n)

  window_start <- 1L

  while(params$position <= params$n) {
    i_position <- i[[params$position]]

    range_stop <- range_stops[[params$position]]
    check_na_range(range_stop, ".after")

    range_stop_positive <- is_range_stop_positive(i_position, range_stop)
    window_stop <- locate_window_stop(params$position, i, range_stop, params$n, range_stop_positive, params$complete)

    if (is.na(window_stop)) {
      params <- increment_by_one(params)
      next
    }

    out <- slice_eval_assign(out, x, f, window_start, window_stop, params, ...)

    params <- increment_by_step(params)
  }

  out
}

loop_double_unbounded <- function(x, f, params, ...) {
  out <- vec_init(params$ptype, params$n)

  window_start <- 1L
  window_stop <- params$n

  while(params$position <= params$n) {
    out <- slice_eval_assign(out, x, f, window_start, window_stop, params, ...)
    params <- increment_by_step(params)
  }

  out
}

# ------------------------------------------------------------------------------

increment_by_one <- function(params) {
  params$position <- params$position + 1L
  params$entry <- params$entry + 1L
  params
}

increment_by_step <- function(params) {
  params$position <- params$position + params$step
  params$entry <- params$entry + params$step
  params
}

# ------------------------------------------------------------------------------

slice_eval_assign <- function(out, x, f, window_start, window_stop, params, ...) {
  slice <- vec_slice(x, seq2(window_start, window_stop))

  elt <- f(slice, ...)

  if (params$constrain) {
    elt <- vec_cast(elt, ptype)

    if (vec_size(elt) != 1L) {
      abort(sprintf("The size of each result of `.f` must be size 1. Iteration %i was size %i.", params$position, vec_size(elt)))
    }

    out <- vec_assign(out, params$entry, elt)
  } else {
    out[[params$entry]] <- elt
  }

  out
}

# ------------------------------------------------------------------------------

slide_index <- function(.x,
                        .i,
                        .f,
                        ...,
                        .before = 0L,
                        .after = 0L,
                        .step = 1L,
                        .complete = FALSE
                        ) {
  slide_index_impl(
    .x,
    .i,
    .f,
    ...,
    .before = .before,
    .after = .after,
    .step = .step,
    .complete = .complete,
    .constrain = FALSE,
    .ptype = list()
  )
}
