# Workflow derived from https://github.com/posit-dev/air-action/tree/main/examples
on:
  push:
    branches: [main, master]
  pull_request:

name: format-check.yaml

permissions: read-all

jobs:
  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format check
        uses: posit-dev/air-action@v1
        with:
          args: format . --check
