# Workflow derived from https://github.com/posit-dev/air-action/tree/main/examples
on:
  pull_request:

name: format-suggest.yaml

permissions: read-all

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Format
        uses: posit-dev/air-action@v1
        with:
          args: format .

      - name: Suggest changes
        uses: reviewdog/action-suggester@v1
        with:
          level: error
          fail_level: error
          tool_name: air
